### ISSUE TITLE
Problema

### ISSUE THREAD

**Issue by vbf1** [ICEI-PUC-Minas-PMV-SInt/pmv-sint-2023-2-e3-proj-back-t1-erp-para-produtores-rurais#2]
Especificação do Problema- buscar dentro do tema, um problema que deseja resolver.

**Comment by Cleidenascimentto** [comment]
Os produtores rurais sofrem com a necessidade de uma gestão empresarial mais eficiente, pois a ausência desta gestão tem gerado efeitos de diminuição do lucro e produtividade. Os principais fatores que tem gerado dificuldades de gestão são: descontrole no estoque, inexistência de relatórios, perda de dados importantes e a improdutividade com planilhas Excel. Diante desses desafios, com este projeto pretendesse gerar uma solução para superar os problemas e garantir produtividade do negócio.
