### ISSUE TITLE
Editar docs no github

### ISSUE THREAD

**Issue by nonatodiego** [ICEI-PUC-Minas-PMV-SInt/pmv-sint-2023-2-e3-proj-back-t1-erp-para-produtores-rurais#28]

**Comment by LeonardoAlves7** [comment]
Documentação de contexto - OK
Especificação do projeto - falta histórias de usuários e o diagrama de caso de uso que está sendo feito pelo Victor
Metodologia - falta a parte de controle de versão e ferramentas
Projeto de interface - falta o diagrama que está sendo feito pelo Victor
Arquitetura de solução - falta o diagrama que está sendo feito pelo Victor

Fique a vontade para fazer qualquer mudança que achar necessário.
