### ISSUE TITLE
Publico alvo

### ISSUE THREAD

**Issue by vbf1** [ICEI-PUC-Minas-PMV-SInt/pmv-sint-2023-2-e3-proj-back-t1-erp-para-produtores-rurais#3]

**Comment by Cleidenascimentto** [comment]
Embora esta solução possa beneficiar empreendedores e vários perfis de pessoas, o foco desta solução está em pequenos produtores rurais. Desta forma, estabeleceu-se como público-alvo desta solução homens e mulheres entre 20 e 60 anos, empreendedores, produtores rurais, brasileiros, que desejam iniciar ou melhorar a sua gestão do seu negócio e buscam simplicidade para a organização de seus estoques e suas finanças diárias. Podem ser pessoas que se considerem desorganizadas na gestão do seu negócio, ou pessoas que já possuem algum tipo de controle de gestão, mas que deseja utilizar uma ferramenta mais simples, intuitiva que seja eficiente e assertiva.

**Comment by Cleidenascimentto** [comment]
Realizei melhorias no texto

https://sgapucminasbr-my.sharepoint.com/:w:/r/personal/1420555_sga_pucminas_br/_layouts/15/doc2.aspx?sourcedoc=%7B1E48DA8A-B78C-47A5-8D73-1DFEF3957321%7D&file=Projeto%20PUC%20Minas.docx&action=default&mobileredirect=true&DefaultItemOpen=1&ct=1692055593832&wdOrigin=OFFICECOM-WEB.MAIN.EDGEWORTH&cid=a88afca5-f6cd-4b0a-bae6-c7d0a77f6244&wdPreviousSessionSrc=HarmonyWeb&wdPreviousSession=3878acd6-4eda-4490-853a-0361ed07a1e7
