### ISSUE TITLE
H9g - elaborar diagramas de caso de uso da aplicação.

### ISSUE THREAD

**Issue by LeonardoAlves7** [ICEI-PUC-Minas-PMV-SInt/pmv-sint-2023-2-e3-proj-back-t1-erp-para-produtores-rurais#34]
Observação: Casos de uso que exigem autenticação devem ter relação de inclusão com o caso de uso Efetuar Login. Alterar Visualizar Produtos para Gerenciar Produtos, alterar Visualizar Insumos para Gerenciar Insumos. Excluir caso de uso CRUD. Gerenciar compras e gerenciar despesas?

**Comment by Cleidenascimentto** [comment]
@vbf1 por gentileza adiciona todos os membros do  grupo no  time  do whimiscal
